@extends('layouts.app')
@section('styles')
    @livewireStyles()
@endsection
@section('scripts')
    @livewireScripts()
@endsection
@section('contents')
    @livewire('cricket.contestType')
@endsection
