<?php

return [
    'STATUS_BAD_REQUEST' => 400,
    'STATUS_UNAUTHORIZED' => 401,
    'TOO_MANY_REQUESTS' => 429,
    'STATUS_CREATED' => 201,
    'STATUS_OK' => 200,
    'STATUS_GENERAL_ERROR' => 500,
    'STATUS_FORBIDDEN' => 403,
    'STATUS_NOT_FOUND' => 404,
    'STATUS_METHOD_NOT_ALLOWED' => 405,
    'STATUS_ALREADY_EXIST' => 409,
    'UNPROCESSABLE_ENTITY' => 422,
    'STATUS_LINK_EXPIRED' => 410,
];
